services:
  database:
    image: cb-mysql-db
    build:
      context: ./
      dockerfile: Dockerfile-db
    volumes:
      - db_data:/var/lib/mysql
    env_file:
      - .env
    ports:
      - "${MYSQL_PORT}:${MYSQL_PORT}"
    container_name: cb-mysql
  redis:
    image: redis:6.2.4
    volumes:
      - /redis/data
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    container_name: cb-redis
  ws_server: 
    depends_on:
      - redis
    image: cb-ws-server
    build:
      context: ./
      dockerfile: Dockerfile-ws
    env_file:
      - .env
    ports:
      - "${BO_WEBSOCKET_PORT}:${BO_WEBSOCKET_PORT}"
  backend:
    depends_on:
      - database
    image: cb-backend
    build:
      context: ./
      dockerfile: Dockerfile-backend
    env_file:
      - .env
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
volumes:
  db_data:
